[US-152] [US-153]Allow no cmap for truetype fonts.
unidoc/freetype pull request #4
Opened 2023-10-16 14:37 UTC by anovik

The aim of this PR is to address [US-152] and [US-153]. Previously we could not use embedded fonts without cmap but it turns out we can use some of them, with Identity-H or Identity-V encodings. 

For this purpose, if for TrueType font we haven't found cmap, we don't return an error now, but instead raise hasNoCmap flag. 

On unipdf side, we check if this flag is raised for identity encoded embedded font - we use it and do not search for a replacement. It is useful mostly for Asian fonts.

Another minor change is to allow hhea length > 36 for TrueType. They still can't have hhea length < 36.

2023-10-16 15:19 UTC, sampila requested changes
Overall looks good, added a comment

2023-10-16 15:19 UTC, sampila commented on truetype/truetype.go
> +}
Probably better to rename it as `HasCmap`?

2023-10-16 17:04 UTC, anovik commented on truetype/truetype.go
> +}
@sampila Changed to HasCmap

2023-10-17 02:08 UTC, sampila approved these changes
Looks good to me

2023-10-17 17:29 UTC, gunnsth approved these changes
LGTM

2023-10-17 17:29 UTC, merged